[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-skill-wolfie"
dynamic = ["version"]
description = "ovos wolfram alpha skill plugin"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "JarbasAi", email = "jarbasai@mailfence.com"}
]
keywords = ["ovos", "skill", "plugin", "wolfram"]
dependencies = [
    "ovos-utils>=0.7.0,<1.0.0",
    "ovos-workshop>=8.0.0,<9.0.0",
    "ovos-wolfram-alpha-plugin>=1.0.0a1,<2.0.0"
]

[project.optional-dependencies]
test = [
    "ovoscope>=1.5.0a1",
    "padacioso>=1.1.1a1"
]

[project.urls]
Homepage = "https://github.com/OpenVoiceOS/ovos-skill-wolfie"

[project.entry-points."ovos.plugin.skill"]
"ovos-skill-wolfie.openvoiceos" = "ovos_skill_wolfie:WolframAlphaSkill"

[tool.setuptools.dynamic]
version = {attr = "ovos_skill_wolfie.version.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["ovos_skill_wolfie*"]

[tool.setuptools.package-data]
ovos_skill_wolfie = [
    "*.json",
    "*.gif",
    "locale/**/*",
    "gui/**/*",
]
