"""E2E intent-routing tests for ovos-skill-wolfie.

Auto-generated by tools/gen_ovoscope_tests.py
Run: pytest test/end2end/ -v
"""
from unittest import TestCase

from ovos_bus_client.message import Message
from ovos_bus_client.session import Session
from ovoscope import End2EndTest, get_minicroft

SKILL_ID = "ovos-skill-wolfie.openvoiceos"
LANG = "en-US"


class _IntentRoutingMixin:
    """Shared MiniCroft setup."""

    @classmethod
    def setUpClass(cls):
        cls.minicroft = get_minicroft([SKILL_ID])

    @classmethod
    def tearDownClass(cls):
        if getattr(cls, 'minicroft', None):
            cls.minicroft.stop()


    def _assert_padacioso(self, utterance: str, intent_file: str):
        intent_msg_type = f"{SKILL_ID}:{intent_file}"
        session = Session(f"e2e-en_us-{intent_file}-{hash(utterance)}")
        session.lang = LANG
        session.pipeline = ["ovos-padacioso-pipeline-plugin-medium"]
        message = Message(
            "recognizer_loop:utterance",
            {"utterances": [utterance], "lang": LANG},
            {"session": session.serialize()},
        )
        test = End2EndTest(
            minicroft=self.minicroft,
            skill_ids=[SKILL_ID],
            eof_msgs=["ovos.utterance.handled"],
            flip_points=["recognizer_loop:utterance"],
            source_message=message,
            activation_points=[intent_msg_type],
            test_msg_context=False,
            expected_messages=[
                message,
                Message(f"{SKILL_ID}.activate", {}, {"skill_id": SKILL_ID}),
                Message(intent_msg_type, {}, {"skill_id": SKILL_ID}),
                Message("mycroft.skill.handler.start", {}, {"skill_id": SKILL_ID}),
                Message("mycroft.skill.handler.complete", {}, {"skill_id": SKILL_ID}),
                Message("ovos.utterance.handled", {}, {"skill_id": SKILL_ID}),
            ],
        )
        test.execute(timeout=30)


class TestPadacioso1_Search_wolfie_intent(_IntentRoutingMixin, TestCase):
    """Padacioso intent: search_wolfie.intent"""
    def test_ask_the_wolf_something(self):
        self._assert_padacioso(r"ask the wolf something", r"search_wolfie.intent")

    def test_ask_the_wolfram_about_something(self):
        self._assert_padacioso(r"ask the wolfram about something", r"search_wolfie.intent")

    def test_ask_the_wolfram_alpha_about_something(self):
        self._assert_padacioso(r"ask the wolfram alpha about something", r"search_wolfie.intent")

    def test_search_the_wolf_for_something(self):
        self._assert_padacioso(r"search the wolf for something", r"search_wolfie.intent")

    def test_search_wolfram_alpha_for_something(self):
        self._assert_padacioso(r"search wolfram alpha for something", r"search_wolfie.intent")
